---
# tasks - main.yml for nerve4-chrony

- include_tasks: rhel.yml
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
